# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo requirements.txt en el directorio de trabajo
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de la aplicación en el directorio de trabajo
COPY . .

# Expone el puerto 5000 para la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "app_buckets.py"]
